@baseURL = http://localhost:4000
@id = 60bbe781d91e21081ccf1901

###
// GET - Lista livros
GET {{baseURL}}/livros
Content-Type: application/json

###
// GET - Lista livros - INVÁLIDO
GET {{baseURL}}/livro
Content-Type: application/json

###
// GET - Lista livro por id
GET {{baseURL}}/livros/{{id}}
Content-Type: application/json

###
// GET - Lista apenas uma categoria pelo id - INVÁLIDO
GET {{baseURL}}/livros/44
Content-Type: application/json

###
// POST - Inclui livro
POST {{baseURL}}/livros
Content-Type: application/json

{
    "nome": "Ladrão de Casaca",
    "autor": "Maurice Leblanc",
    "genero": "Romance policial",
    "ano_lancamento": 1907,
    "url_img":"https://m.media-amazon.com/images/I/51oKfp5K4YL._SY346_.jpg",
    "link_compra":"https://www.americanas.com.br/produto/3319251961?opn=YSMESP&sellerid=02"
}

###
// POST - Inclui livro - INVÁLIDO
POST {{baseURL}}/livros
Content-Type: application/json

{
    "nomee": "Orgulho e preconceito",
    "autor": "Jane Austen",
    "genero": "Romance de amor",
    "ano_lancamento": 1813,
    "url_img":"https://images-na.ssl-images-amazon.com/images/I/511c2+CJ30L._SY344_BO1,204,203,200_.jpg",
    "link_compra":"https://www.americanas.com.br/produto/133434582?opn=YSMESP&sellerid=02"
}


### 
// DELETE - Apaga uma livro através do id informado
DELETE {{baseURL}}/livros/{{id}}
Content-Type: application/json

### 
// DELETE - Apaga uma livro com id - INVÁLIDO
DELETE {{baseURL}}/livros/{{id}}
Content-Type: application/json

###
// PUT - Altera uma livro pelo ID
PUT {{baseURL}}/livros
Content-Type: application/json

{
    "_id": "60b7702cb1630a0670bd3826", 
    "nome": "Ladrão de Casaca",
    "autor": "Maurice Leblanc",
    "url_img":"https://a-static.mlcdn.com.br/1500x1500/livro-arsene-lupin-o-ladrao-de-casaca/livrariauniversodolivro/595p/745171392f44202a8a94ff670cc2f176.jpg"
}


###
// PUT - Altera uma livro pelo ID - INVÁLIDO
PUT {{baseURL}}/livros
Content-Type: application/json

{
    "_id": "111", 
    "nome": "Orgulho e preconceito",
    "autor": "Jane Austen"
}
